const sidebars = {
  documentacionSidebar: [
    {
      type: 'category',
      label: 'Documentación',
      items: [
        'documentacion/contable/index',
        'documentacion/nomina/index',
        'documentacion/ISV/index',
      ],
    },
  ],
  casosSidebar: [
    {
      type: 'category',
      label: 'Casos comunes',
      items: [
        'casos/acceso-usuarios/index',
        'casos/descuadres-nomina/index',
        'casos/errores-plataforma/index',
      ],
    },
  ],
  menuContabilidad: [{ type: 'autogenerated', dirName: 'cursos/curso-contabilidad' }],
  menuNomina: [{ type: 'autogenerated', dirName: 'cursos/curso-nomina' }],
};

export default sidebars;
