const sidebars = {

  documentacionSidebar: [

    {
      type: 'category',
      label: 'ISV',
      items: [
        'documentacion/isvleo/pruebasleo',
        'documentacion/isvleo/pruebasleo 2',
        'documentacion/isvleo/pruebasleo 3',
      ],
    },

    {
      type: 'category',
      label: 'NOMINA',
      items: [
        'documentacion/nomina/calculos',
        'documentacion/nomina/contratos',
        'documentacion/nomina/novedades',
      ],
    },

    {
      type: 'category',
      label: 'CONTABILIDAD',
      items: [
        'documentacion/contabilidadpablo/pruebaspablo',
        'documentacion/contabilidadpablo/pruebaspablo2',
        'documentacion/contabilidadpablo/pruebaspablo3',
      ],
    },

  ],

  casosSidebar: [

    {
      type: 'category',
      label: 'Casos comunes',
      items: [
        'casos/acceso-usuarios/index',
        'casos/descuadres-nomina/index',
        'casos/errores-plataforma/index',
      ],
    },

  ],

  menuContabilidad: [
    {
      type: 'autogenerated',
      dirName: 'cursos/curso-contabilidad',
    },
  ],

  menuNomina: [
    {
      type: 'autogenerated',
      dirName: 'cursos/curso-nomina',
    },
  ],

  menuISV: [
    {
      type: 'autogenerated',
      dirName: 'cursos/curso-isv',
    },
  ],

};

export default sidebars;