const sidebars = {
  documentacionSidebar: [
    {
      type: 'category',
      label: 'contabilidad',
      items: [
        'isvleo/pruebasleo',
        'nomina/contratos',
        'nomina/novedades',
      ],
    },
    {
      type: 'category',
      label: 'nomina',
      items: [
        'nomina/calculos',
        'nomina/contratos',
        'nomina/novedades',
      ],
    },
  ],
  casosSidebar: [
    {
      type: 'category',
      label: 'Casos comunes',
      items: [
        'casos/acceso-usuarios/index',
        'casos/descuadres-nomina/index',
        'casos/errores-plataforma/index',
      ],
    },
  ],
  menuContabilidad: [{ type: 'autogenerated', dirName: 'cursos/curso-contabilidad' }],
  menuNomina: [{ type: 'autogenerated', dirName: 'cursos/curso-nomina' }],
};

export default sidebars;
